language: cpp
env:
  global:
    - DEPS=""
matrix:
  include:
    # Temporarilly disable osx => https://git.io/JLp7U
    # - os: osx
    #   compiler: clang
    #   osx_image: xcode9.4
    #   env:
    #     - DEPS="${DEPS} readline llvm@6"
    #     - LLVM_DIR=/usr/local/opt/llvm@6/lib/cmake/llvm/
    #     - ARGS=-V
    - os: linux
      compiler: g++
      root: required
      dist: trusty
      group: deprecated-2017Q4
      services:
        - docker
      env:
        - DIST=xenial
        - DEPS="llvm-3.7-dev cmake libedit-dev g++ libncurses5-dev zlib1g-dev libreadline-dev python2.7"
        - ARGS=-V
        
    - os: linux
      compiler: g++
      root: required
      dist: trusty
      group: deprecated-2017Q4
      services:
        - docker
      env:
        - DIST=xenial
        - DEPS="llvm-4.0-dev cmake libedit-dev g++ libncurses5-dev zlib1g-dev libreadline-dev python2.7"
        - ARGS=-V
        
    - os: linux
      compiler: g++
      root: required
      dist: trusty
      group: deprecated-2017Q4
      services:
        - docker
      env:
        - DIST=xenial
        - DEPS="llvm-6.0-dev cmake libedit-dev g++ libncurses5-dev zlib1g-dev libreadline-dev python2.7"
        - ARGS=-V
        
    - os: linux
      compiler: g++
      language: nix
      nix: 2.3.6
      group: deprecated-2017Q4
      script: nix-build
      script: nix-build --expr 'with import (fetchTarball { url="https://github.com/NixOs/nixpkgs/archive/a3ab47ec9067b5f9fccda506fc8641484c3d8e73.tar.gz"; sha256="1f1q89ka73ksvl5hgbrf624x0niwm2rg3dzxiscir0bji6zvjy15"; }) {}; stdenv.mkDerivation { name="hobbes"; src=./.; nativeBuildInputs=[ llvm_6 cmake ninja python27 readline zlib gcc10 ]; doCheck=true; checkTarget="test"; }' 

    - os: linux
      compiler: g++
      language: nix
      nix: 2.3.6
      group: deprecated-2017Q4
      script: nix-build
      script: nix-build --expr 'with import (fetchTarball { url="https://github.com/NixOs/nixpkgs/archive/a3ab47ec9067b5f9fccda506fc8641484c3d8e73.tar.gz"; sha256="1f1q89ka73ksvl5hgbrf624x0niwm2rg3dzxiscir0bji6zvjy15"; }) {}; stdenv.mkDerivation { name="hobbes"; src=./.; nativeBuildInputs=[ llvm_8 cmake ninja python27 readline zlib gcc10 ]; doCheck=true; checkTarget="test"; }' 

    - os: linux
      compiler: g++
      language: nix
      nix: 2.3.6
      group: deprecated-2017Q4
      script: nix-build
      script: nix-build --expr 'with import (fetchTarball { url="https://github.com/NixOs/nixpkgs/archive/a3ab47ec9067b5f9fccda506fc8641484c3d8e73.tar.gz"; sha256="1f1q89ka73ksvl5hgbrf624x0niwm2rg3dzxiscir0bji6zvjy15"; }) {}; stdenv.mkDerivation { name="hobbes"; src=./.; nativeBuildInputs=[ llvm_9 cmake ninja python27 readline zlib gcc10 ]; doCheck=true; checkTarget="test"; }' 

    - os: linux
      compiler: g++
      language: nix
      nix: 2.3.6
      group: deprecated-2017Q4
      script: nix-build
      script: nix-build --expr 'with import (fetchTarball { url="https://github.com/NixOs/nixpkgs/archive/a3ab47ec9067b5f9fccda506fc8641484c3d8e73.tar.gz"; sha256="1f1q89ka73ksvl5hgbrf624x0niwm2rg3dzxiscir0bji6zvjy15"; }) {}; stdenv.mkDerivation { name="hobbes"; src=./.; nativeBuildInputs=[ llvm_10 cmake ninja python27 readline zlib gcc10 ]; doCheck=true; checkTarget="test"; }' 

install:
  - if [ $TRAVIS_OS_NAME = osx   ]; then brew update && brew install -v ${DEPS} && find /usr/local/opt/llvm@6/ | grep cmake; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then cd docker/build && docker build . -f ./${DIST}.Dockerfile -t hobbes:build --build-arg DEPS; cd -; fi

script:
  - if [ $TRAVIS_OS_NAME = osx   ]; then mkdir build && cd build/ && cmake .. && make && make test; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then docker run -it -v ${PWD}:/src hobbes:build; fi

branches:
  only:
    - master
    - travis
