language: cpp
env:
  global:
    - DEPS=""
matrix:
  include:
    # - os: linux
    #   compiler: clang
    #   language: nix
    #   nix: 2.3.10
    #   group: edge
    #   dist: focal
    #   name: hobbesPackages.clang-6.hobbes
    #   env:
    #     - HOBBES_DRV=hobbesPackages.clang-6.hobbes
    #   script: travis_wait 40 nix-build -A $HOBBES_DRV

    # # - os: osx
    # #   osx_image: xcode10.12 # 12.12
    # #   compiler: clang
    # #   language: nix
    # #   nix: 2.3.10
    # #   group: edge
    # #   name: hobbesPackages.clang-6.hobbes
    # #   env:
    # #     - HOBBES_DRV=hobbesPackages.clang-6.hobbes
    # #   script: travis_wait 40 nix-build -A $HOBBES_DRV

    # - os: linux
    #   compiler: clang
    #   language: nix
    #   nix: 2.3.10
    #   group: edge
    #   dist: focal
    #   name: hobbesPackages.clang-8.hobbes
    #   env:
    #     - HOBBES_DRV=hobbesPackages.clang-8.hobbes
    #   script: travis_wait 40 nix-build -A $HOBBES_DRV

    # - os: linux
    #   compiler: g++
    #   language: nix
    #   nix: 2.3.10
    #   group: edge
    #   dist: focal
    #   name: hobbesPackages.gcc-8.llvm-8.hobbes
    #   env:
    #     - HOBBES_DRV=hobbesPackages.gcc-8.llvm-8.hobbes
    #   script: travis_wait 40 nix-build -A $HOBBES_DRV

    # # - os: osx
    # #   osx_image: xcode10.12 # 12.12
    # #   compiler: clang
    # #   language: nix
    # #   nix: 2.3.10
    # #   group: edge
    # #   name: hobbesPackages.clang-8.hobbes
    # #   env:
    # #     - HOBBES_DRV=hobbesPackages.clang-8.hobbes
    # #   script: travis_wait 40 nix-build -A $HOBBES_DRV

    # - os: linux
    #   compiler: clang
    #   language: nix
    #   nix: 2.3.10
    #   group: edge
    #   dist: focal
    #   name: hobbesPackages.clang-9.hobbes
    #   env:
    #     - HOBBES_DRV=hobbesPackages.clang-9.hobbes
    #   script: travis_wait 40 nix-build -A $HOBBES_DRV

    # - os: linux
    #   compiler: g++
    #   language: nix
    #   nix: 2.3.10
    #   group: edge
    #   dist: focal
    #   name: hobbesPackages.gcc-9.llvm-9.hobbes
    #   env:
    #     - HOBBES_DRV=hobbesPackages.gcc-9.llvm-9.hobbes
    #   script: travis_wait 40 nix-build -A $HOBBES_DRV

    # # - os: osx
    # #   osx_image: xcode10.12 # 12.12
    # #   compiler: clang
    # #   language: nix
    # #   nix: 2.3.10
    # #   group: edge
    # #   name: hobbesPackages.clang-9.hobbes
    # #   env:
    # #     - HOBBES_DRV=hobbesPackages.clang-9.hobbes
    # #   script: travis_wait 40 nix-build -A $HOBBES_DRV

    # - os: linux
    #   compiler: clang
    #   language: nix
    #   nix: 2.3.10
    #   group: edge
    #   dist: focal
    #   name: hobbesPackages.clang-10.hobbes
    #   env:
    #     - HOBBES_DRV=hobbesPackages.clang-10.hobbes
    #   script: travis_wait 40 nix-build -A $HOBBES_DRV

    # - os: linux
    #   compiler: g++
    #   language: nix
    #   nix: 2.3.10
    #   group: edge
    #   dist: focal
    #   name: hobbesPackages.gcc-10.llvm-10.hobbes
    #   env:
    #     - HOBBES_DRV=hobbesPackages.gcc-10.llvm-10.hobbes
    #   script: travis_wait 40 nix-build -A $HOBBES_DRV

    # # - os: osx
    # #   osx_image: xcode10.12 # 12.12
    # #   compiler: clang
    # #   language: nix
    # #   nix: 2.3.10
    # #   group: edge
    # #   name: hobbesPackages.clang-10.hobbes
    # #   env:
    # #     - HOBBES_DRV=hobbesPackages.clang-10.hobbes
    # #   script: travis_wait 40 nix-build -A $HOBBES_DRV
      
    # - os: linux
    #   compiler: clang
    #   language: nix
    #   nix: 2.3.10
    #   group: edge
    #   dist: focal
    #   name: hobbesPackages.clang-11.hobbes
    #   env:
    #     - HOBBES_DRV=hobbesPackages.clang-11.hobbes
    #   script: travis_wait 40 nix-build -A $HOBBES_DRV

    # - os: linux
    #   compiler: g++
    #   language: nix
    #   nix: 2.3.10
    #   group: edge
    #   dist: focal
    #   name: hobbesPackages.gcc-10.llvm-11.hobbes
    #   env:
    #     - HOBBES_DRV=hobbesPackages.gcc-10.llvm-11.hobbes
    #   script: travis_wait 40 nix-build -A $HOBBES_DRV

    - os: osx
      osx_image: xcode10.12 # 12.12
      compiler: clang
      language: nix
      nix: 2.3.10
      group: edge
      name: hobbesPackages.clang-8.hobbes
      env:
        - HOBBES_DRV=hobbesPackages.clang-8.hobbes
      script: travis_wait 40 nix-build -A $HOBBES_DRV
        
branches:
  only:
    - master
    - travis
