name: "Build"
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        clang: [6, 8, 10, 11]
        include:
          - os: macos-latest
            experimental: true
    steps:
      - uses: actions/checkout@v2
        with:
            # Nix Flakes doesn't work on shallow clones
            fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes ca-references
      - name: nix build hobbesPackages/clang-${{ matrix.clang }}/hobbes
        run: |
          nix build .#hobbesPackages/clang-${{ matrix.clang }}/hobbes
          nix log  .#hobbesPackages/clang-${{ matrix.clang }}/hobbes &> clang-${{ matrix.clang }}-hobbes.log
      - name: upload log hobbesPackages/clang-${{ matrix.clang }}/hobbes
        uses: actions/upload-artifact@v1
        with:
          name: output-log-file
          path: clang-${{ matrix.clang }}-hobbes.log

